spring.application.name=testGeminiAI

spring.application.name=testGeminiAI

# Clave de API de Google AI Studio
spring.ai.google.genai.api-key=${GEMINI_API_KEY}

# Modelo a utilizar
spring.ai.google.genai.chat.options.model=gemini-3.8-flash