spring.application.name=testGeminiAI

spring.application.name=testGeminiAI

# Clave de API de Google AI Studio
spring.ai.google.genai.api-key=AQ.Ab8RN6LNdNVDXjXQVh8sxUlU7hdkN4miyfi5rBA9QqxHn3dtzQ

# Modelo a utilizar
spring.ai.google.genai.chat.options.model=gemini-3.8-flash