spring.application.name=testSpringAI

# URL base apuntando a Groq
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.api-key=${GROQ_API_KEY}
# Modelo gratuito disponible en Groq
spring.ai.openai.chat.options.model=openai/gpt-oss-20b
