spring.datasource.url=jdbc:mysql://localhost:3306/db_persona_2b?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Puerto del servidor
server.port=9001

server.error.include-message=always
server.error.include-binding-errors=always


# Configuración java mail sender (SMTP)

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pruebamailsender011@gmail.com
spring.mail.password=unsatiivcwhdseyj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# Configuración de notificaciones

# URL de la facultad para el botón en el correo de cumpleaños
app.facultad.url=https://ingenieria.uncuyo.edu.ar/

# Remitente para correos salientes
app.mail.from=pruebamailsender011@gmail.com

# Expresiones CRON para Spring Scheduling
# Por defecto se ejecutan todos los días a las 08:00 AM
# Formato CRON de Spring: segundo minuto hora día mes día-de-semana
app.scheduling.cron-vencimiento=${CRON_VENCIMIENTO:0 0 8 * * *}
app.scheduling.cron-cumpleanios=${CRON_CUMPLEANIOS:0 0 8 * * *}
