spring.datasource.url=jdbc:mysql://localhost:3306/db_persona_1d?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Variable de entorno
server.port=9001

server.error.include-message=always
server.error.include-binding-errors=always

# Configuracion de almacenamiento para libros PDF (Linux / Entornos configurables)
biblioteca.storage.path=${STORAGE_PATH:${user.home}/biblioteca_1d}

# Limites de carga de archivos multipart
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
